<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE data [
<!ELEMENT data (channelid, onairdate, onairflag, onairno, events)>
<!ELEMENT channelid (#PCDATA)>
<!ELEMENT onairdate (#PCDATA)>
<!ELEMENT onairflag (#PCDATA)>
<!ELEMENT onairno (#PCDATA)>
<!ELEMENT eventcount (#PCDATA)>
<!ELEMENT events (event*)>
<!ELEMENT event (#PCDATA)>
<!ATTLIST event serialno CDATA #REQUIRED programno CDATA #REQUIRED groupno CDATA #REQUIRED eventmode CDATA #REQUIRED "1" startmode CDATA "0" starttime CDATA input CDATA output CDATA title CDATA #REQUIRED subtitle CDATA source CDATA mediaid CDATA durationtc CDATA intc CDATA outtc CDATA videotype CDATA audiotype CDATA closedcaption CDATA voiceadd CDATA transitiontype CDATA transitionrate CDATA programtype CDATA notes CDATA>
]>
<data>
  <channelid>3</channelid>
  <onairdate>20190930</onairdate>
  <onairflag>r</onairflag>
  <onairno>0</onairno>
  <eventcount>199</eventcount>
  <events>
    <event serialno="0" programno="1602" groupno="1602" eventmode="1" startmode="0" starttime="20190930 06:54:02:00" input="0" output="3" title="Sign On" subtitle="EBS Plus2 Sign On&lt;4차&gt;2019년9월30일(월)" source="PLUS2_DEC1" mediaid="6B190020" durationtc="00:04:33:00" intc="00:00:00:00" outtc="00:04:32:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="1" programno="1602" groupno="1602" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="Sign On" subtitle="EBS Plus2 Sign On&lt;4차&gt;2019년9월30일(월)" source="PLUS2_DEC2" mediaid="6B190020" durationtc="00:04:33:00" intc="00:00:00:00" outtc="00:04:32:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="2" programno="1603" groupno="1603" eventmode="1" startmode="0" starttime="20190930 06:58:35:00" input="0" output="3" title="공익광고" subtitle="안전불감증 개선&lt;어느 안전&gt;(30&quot;)" source="PLUS2_DEC1" mediaid="2B190143" durationtc="00:00:30:00" intc="00:00:00:00" outtc="00:00:29:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="3" programno="1603" groupno="1603" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="공익광고" subtitle="안전불감증 개선&lt;어느 안전&gt;(30&quot;)" source="PLUS2_DEC2" mediaid="2B190143" durationtc="00:00:30:00" intc="00:00:00:00" outtc="00:00:29:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="4" programno="1604" groupno="1604" eventmode="1" startmode="0" starttime="20190930 06:59:05:00" input="0" output="3" title="공익광고" subtitle="재난대비 국민행동요령&lt;아프리카돼지열병(A" source="PLUS2_DEC1" mediaid="2B190147" durationtc="00:00:55:00" intc="00:00:00:00" outtc="00:00:54:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="5" programno="1604" groupno="1604" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="공익광고" subtitle="재난대비 국민행동요령&lt;아프리카돼지열병(A" source="PLUS2_DEC2" mediaid="2B190147" durationtc="00:00:55:00" intc="00:00:00:00" outtc="00:00:54:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="6" programno="1605" groupno="1605" eventmode="1" startmode="0" starttime="20190930 07:00:00:00" input="0" output="3" title="경비지도사 시험대비 강좌" subtitle="법학개론 제1강" source="PLUS2_DEC1" mediaid="N199J230" durationtc="00:29:05:00" intc="00:00:00:00" outtc="00:29:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="7" programno="1605" groupno="1605" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="경비지도사 시험대비 강좌" subtitle="법학개론 제1강" source="PLUS2_DEC2" mediaid="N199J230" durationtc="00:29:05:00" intc="00:00:00:00" outtc="00:29:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="8" programno="1606" groupno="1606" eventmode="1" startmode="0" starttime="20190930 07:29:05:00" input="0" output="3" title="SPOT" subtitle="EBS Math 홍보&lt;수학은 즐겁고 창의적인 놀?" source="PLUS2_DEC1" mediaid="1B191251" durationtc="00:00:49:00" intc="00:00:00:00" outtc="00:00:48:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="9" programno="1606" groupno="1606" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="SPOT" subtitle="EBS Math 홍보&lt;수학은 즐겁고 창의적인 놀?" source="PLUS2_DEC2" mediaid="1B191251" durationtc="00:00:49:00" intc="00:00:00:00" outtc="00:00:48:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="10" programno="1607" groupno="1607" eventmode="1" startmode="0" starttime="20190930 07:29:54:00" input="0" output="3" title="ID" subtitle="EBS PLUS2&lt;직업교육&gt;" source="PLUS2_DEC1" mediaid="3B181264" durationtc="00:00:28:00" intc="00:00:00:00" outtc="00:00:27:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="11" programno="1607" groupno="1607" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="ID" subtitle="EBS PLUS2&lt;직업교육&gt;" source="PLUS2_DEC2" mediaid="3B181264" durationtc="00:00:28:00" intc="00:00:00:00" outtc="00:00:27:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="12" programno="1608" groupno="1608" eventmode="1" startmode="0" starttime="20190930 07:30:22:00" input="0" output="3" title="생활스포츠지도사 시험대비 강좌" subtitle="스포츠심리학 - 운동제어와 운동학습" source="PLUS2_DEC1" mediaid="N1988143" durationtc="00:28:48:00" intc="00:00:00:00" outtc="00:28:47:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="13" programno="1608" groupno="1608" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="생활스포츠지도사 시험대비 강좌" subtitle="스포츠심리학 - 운동제어와 운동학습" source="PLUS2_DEC2" mediaid="N1988143" durationtc="00:28:48:00" intc="00:00:00:00" outtc="00:28:47:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="14" programno="1609" groupno="1609" eventmode="1" startmode="0" starttime="20190930 07:59:10:00" input="0" output="3" title="공익광고" subtitle="성매매 방지&lt;그것도 성매매&gt;(40&quot;)" source="PLUS2_DEC1" mediaid="2B180068" durationtc="00:00:40:00" intc="00:00:00:00" outtc="00:00:39:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="15" programno="1609" groupno="1609" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="공익광고" subtitle="성매매 방지&lt;그것도 성매매&gt;(40&quot;)" source="PLUS2_DEC2" mediaid="2B180068" durationtc="00:00:40:00" intc="00:00:00:00" outtc="00:00:39:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="16" programno="1610" groupno="1610" eventmode="1" startmode="0" starttime="20190930 07:59:50:00" input="0" output="3" title="ID" subtitle="EBS 로고송 MAIN&lt;이진아(2)&gt;(알려줘 Ver.)(" source="PLUS2_DEC1" mediaid="3B190211" durationtc="00:00:27:00" intc="00:00:00:00" outtc="00:00:26:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="17" programno="1610" groupno="1610" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="ID" subtitle="EBS 로고송 MAIN&lt;이진아(2)&gt;(알려줘 Ver.)(" source="PLUS2_DEC2" mediaid="3B190211" durationtc="00:00:27:00" intc="00:00:00:00" outtc="00:00:26:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="18" programno="1611" groupno="1611" eventmode="1" startmode="0" starttime="20190930 08:00:17:00" input="0" output="3" title="경비지도사 시험대비 강좌(재)" subtitle="법학개론 제1강" source="PLUS2_DEC1" mediaid="N199J230" durationtc="00:29:05:00" intc="00:00:00:00" outtc="00:29:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="19" programno="1611" groupno="1611" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="경비지도사 시험대비 강좌(재)" subtitle="법학개론 제1강" source="PLUS2_DEC2" mediaid="N199J230" durationtc="00:29:05:00" intc="00:00:00:00" outtc="00:29:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="20" programno="1611" groupno="1611" eventmode="3" startmode="4" starttime="20190930 00:00:10:00" input="2" output="1" title="1.재방송 수퍼" subtitle="재방송 수퍼" source="PLUS2_CG1" mediaid="PLUS20001.tcf" durationtc="00:00:05:00" intc="00:00:00:00" outtc="00:00:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="3" programtype="0" notes=""/>
    <event serialno="21" programno="1612" groupno="1612" eventmode="1" startmode="0" starttime="20190930 08:29:22:00" input="0" output="3" title="캠페인" subtitle="EBS 안전 캠페인-행복을 위한 안전 대피도(" source="PLUS2_DEC1" mediaid="7B180153" durationtc="00:00:47:00" intc="00:00:00:00" outtc="00:00:46:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="22" programno="1612" groupno="1612" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="캠페인" subtitle="EBS 안전 캠페인-행복을 위한 안전 대피도(" source="PLUS2_DEC2" mediaid="7B180153" durationtc="00:00:47:00" intc="00:00:00:00" outtc="00:00:46:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="23" programno="1613" groupno="1613" eventmode="1" startmode="0" starttime="20190930 08:30:09:00" input="0" output="3" title="#검정고시 시험대비 강좌" subtitle="고졸 과학 제1강 우주와 태양계" source="PLUS2_DEC1" mediaid="N191H093" durationtc="00:28:55:00" intc="00:00:00:00" outtc="00:28:54:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="0" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="24" programno="1613" groupno="1613" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="#검정고시 시험대비 강좌" subtitle="고졸 과학 제1강 우주와 태양계" source="PLUS2_DEC2" mediaid="N191H093" durationtc="00:28:55:00" intc="00:00:00:00" outtc="00:28:54:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="25" programno="1614" groupno="1614" eventmode="1" startmode="0" starttime="20190930 08:59:04:00" input="0" output="3" title="캠페인" subtitle="EBS 안전 캠페인-스마트폰 안전(1' 30&quot;)(수" source="PLUS2_DEC1" mediaid="7B180206" durationtc="00:01:30:00" intc="00:00:00:00" outtc="00:01:29:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="26" programno="1614" groupno="1614" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="캠페인" subtitle="EBS 안전 캠페인-스마트폰 안전(1' 30&quot;)(수" source="PLUS2_DEC2" mediaid="7B180206" durationtc="00:01:30:00" intc="00:00:00:00" outtc="00:01:29:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="27" programno="1615" groupno="1615" eventmode="1" startmode="0" starttime="20190930 09:00:34:00" input="0" output="3" title="#보이는 라디오-잉글리시 클리닉" subtitle="156회" source="PLUS2_DEC1" mediaid="N18CR259" durationtc="00:37:23:00" intc="00:00:00:00" outtc="00:37:22:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="0" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="28" programno="1615" groupno="1615" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="#보이는 라디오-잉글리시 클리닉" subtitle="156회" source="PLUS2_DEC2" mediaid="N18CR259" durationtc="00:37:23:00" intc="00:00:00:00" outtc="00:37:22:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="29" programno="1616" groupno="1616" eventmode="1" startmode="0" starttime="20190930 09:37:57:00" input="0" output="3" title="SPOT" subtitle="EBS 교육격차 해소-찾아가는 입시설명회&lt;여" source="PLUS2_DEC1" mediaid="1B191226" durationtc="00:01:19:00" intc="00:00:00:00" outtc="00:01:18:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="30" programno="1616" groupno="1616" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="SPOT" subtitle="EBS 교육격차 해소-찾아가는 입시설명회&lt;여" source="PLUS2_DEC2" mediaid="1B191226" durationtc="00:01:19:00" intc="00:00:00:00" outtc="00:01:18:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="31" programno="1617" groupno="1617" eventmode="1" startmode="0" starttime="20190930 09:39:16:00" input="0" output="3" title="공익광고" subtitle="재난대비 국민행동요령&lt;아프리카돼지열병(A" source="PLUS2_DEC1" mediaid="2B190147" durationtc="00:00:55:00" intc="00:00:00:00" outtc="00:00:54:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="32" programno="1617" groupno="1617" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="공익광고" subtitle="재난대비 국민행동요령&lt;아프리카돼지열병(A" source="PLUS2_DEC2" mediaid="2B190147" durationtc="00:00:55:00" intc="00:00:00:00" outtc="00:00:54:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="33" programno="1618" groupno="1618" eventmode="1" startmode="0" starttime="20190930 09:40:11:00" input="0" output="3" title="ID" subtitle="EBS PLUS2(2019)" source="PLUS2_DEC1" mediaid="3B190325" durationtc="00:00:20:00" intc="00:00:00:00" outtc="00:00:19:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="34" programno="1618" groupno="1618" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="ID" subtitle="EBS PLUS2(2019)" source="PLUS2_DEC2" mediaid="3B190325" durationtc="00:00:20:00" intc="00:00:00:00" outtc="00:00:19:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="35" programno="1619" groupno="1619" eventmode="1" startmode="0" starttime="20190930 09:40:31:00" input="0" output="3" title="매일 10분 영어 - 세리나의 누구나 톡톡" subtitle="톡톡 131. 너무 만만하게 굴지 마." source="PLUS2_DEC1" mediaid="N1994273" durationtc="00:08:31:00" intc="00:00:00:00" outtc="00:08:30:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="36" programno="1619" groupno="1619" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="매일 10분 영어 - 세리나의 누구나 톡톡" subtitle="톡톡 131. 너무 만만하게 굴지 마." source="PLUS2_DEC2" mediaid="N1994273" durationtc="00:08:31:00" intc="00:00:00:00" outtc="00:08:30:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="37" programno="1620" groupno="1620" eventmode="1" startmode="0" starttime="20190930 09:49:02:00" input="0" output="3" title="SPOT" subtitle="EBS Math 홍보&lt;수학은 즐겁고 창의적인 놀?" source="PLUS2_DEC1" mediaid="1B191251" durationtc="00:00:49:00" intc="00:00:00:00" outtc="00:00:48:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="38" programno="1620" groupno="1620" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="SPOT" subtitle="EBS Math 홍보&lt;수학은 즐겁고 창의적인 놀?" source="PLUS2_DEC2" mediaid="1B191251" durationtc="00:00:49:00" intc="00:00:00:00" outtc="00:00:48:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="39" programno="1621" groupno="1621" eventmode="1" startmode="0" starttime="20190930 09:49:51:00" input="0" output="3" title="ID" subtitle="EBS 태양계&lt;화성&gt;" source="PLUS2_DEC1" mediaid="3B181163" durationtc="00:00:20:00" intc="00:00:00:00" outtc="00:00:19:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="40" programno="1621" groupno="1621" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="ID" subtitle="EBS 태양계&lt;화성&gt;" source="PLUS2_DEC2" mediaid="3B181163" durationtc="00:00:20:00" intc="00:00:00:00" outtc="00:00:19:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="41" programno="1622" groupno="1622" eventmode="1" startmode="0" starttime="20190930 09:50:11:00" input="0" output="3" title="#과학 다큐-비욘드(Beyond)" subtitle="지능 만들기" source="PLUS2_DEC1" mediaid="N175T057" durationtc="00:47:32:00" intc="00:00:00:00" outtc="00:47:31:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="0" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="42" programno="1622" groupno="1622" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="#과학 다큐-비욘드(Beyond)" subtitle="지능 만들기" source="PLUS2_DEC2" mediaid="N175T057" durationtc="00:47:32:00" intc="00:00:00:00" outtc="00:47:31:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="43" programno="1623" groupno="1623" eventmode="1" startmode="0" starttime="20190930 10:37:43:00" input="0" output="3" title="캠페인" subtitle="EBS 캠페인-온 세상이 학교다&lt;서울 성동구" source="PLUS2_DEC1" mediaid="7B190151" durationtc="00:01:58:00" intc="00:00:00:00" outtc="00:01:57:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="44" programno="1623" groupno="1623" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="캠페인" subtitle="EBS 캠페인-온 세상이 학교다&lt;서울 성동구" source="PLUS2_DEC2" mediaid="7B190151" durationtc="00:01:58:00" intc="00:00:00:00" outtc="00:01:57:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="45" programno="1624" groupno="1624" eventmode="1" startmode="0" starttime="20190930 10:39:41:00" input="0" output="3" title="ID" subtitle="EBS 로고송 MAIN&lt;이진아(1)&gt;(알려줘 Ver.)(" source="PLUS2_DEC1" mediaid="3B190210" durationtc="00:00:27:00" intc="00:00:00:00" outtc="00:00:26:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="46" programno="1624" groupno="1624" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="ID" subtitle="EBS 로고송 MAIN&lt;이진아(1)&gt;(알려줘 Ver.)(" source="PLUS2_DEC2" mediaid="3B190210" durationtc="00:00:27:00" intc="00:00:00:00" outtc="00:00:26:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="47" programno="1625" groupno="1625" eventmode="1" startmode="0" starttime="20190930 10:40:08:00" input="0" output="3" title="왕초보 영어(전주재방)" subtitle="그만 쿵쾅거려라!" source="PLUS2_DEC1" mediaid="N199K027" durationtc="00:28:40:00" intc="00:00:00:00" outtc="00:28:39:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="0" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="48" programno="1625" groupno="1625" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="왕초보 영어(전주재방)" subtitle="그만 쿵쾅거려라!" source="PLUS2_DEC2" mediaid="N199K027" durationtc="00:28:40:00" intc="00:00:00:00" outtc="00:28:39:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="49" programno="1625" groupno="1625" eventmode="3" startmode="4" starttime="20190930 00:00:10:00" input="2" output="1" title="1.재방송 수퍼" subtitle="재방송 수퍼" source="PLUS2_CG1" mediaid="PLUS20001.tcf" durationtc="00:00:05:00" intc="00:00:00:00" outtc="00:00:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="3" programtype="0" notes=""/>
    <event serialno="50" programno="1626" groupno="1626" eventmode="1" startmode="0" starttime="20190930 11:08:48:00" input="0" output="3" title="SPOT" subtitle="EBS 교육격차 해소-찾아가는 입시설명회&lt;여" source="PLUS2_DEC1" mediaid="1B191226" durationtc="00:01:19:00" intc="00:00:00:00" outtc="00:01:18:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="51" programno="1626" groupno="1626" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="SPOT" subtitle="EBS 교육격차 해소-찾아가는 입시설명회&lt;여" source="PLUS2_DEC2" mediaid="1B191226" durationtc="00:01:19:00" intc="00:00:00:00" outtc="00:01:18:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="52" programno="1627" groupno="1627" eventmode="1" startmode="0" starttime="20190930 11:10:07:00" input="0" output="3" title="매일 10분 영어 - 세리나의 누구나 톡톡(재" subtitle="톡톡 131. 너무 만만하게 굴지 마." source="PLUS2_DEC1" mediaid="N1994273" durationtc="00:08:31:00" intc="00:00:00:00" outtc="00:08:30:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="53" programno="1627" groupno="1627" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="매일 10분 영어 - 세리나의 누구나 톡톡(재" subtitle="톡톡 131. 너무 만만하게 굴지 마." source="PLUS2_DEC2" mediaid="N1994273" durationtc="00:08:31:00" intc="00:00:00:00" outtc="00:08:30:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="54" programno="1627" groupno="1627" eventmode="3" startmode="4" starttime="20190930 00:00:10:00" input="2" output="1" title="1.재방송 수퍼" subtitle="재방송 수퍼" source="PLUS2_CG1" mediaid="PLUS20001.tcf" durationtc="00:00:05:00" intc="00:00:00:00" outtc="00:00:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="3" programtype="0" notes=""/>
    <event serialno="55" programno="1628" groupno="1628" eventmode="1" startmode="0" starttime="20190930 11:18:38:00" input="0" output="3" title="SPOT" subtitle="EBS Math 홍보&lt;수학은 즐겁고 창의적인 놀?" source="PLUS2_DEC1" mediaid="1B191251" durationtc="00:00:49:00" intc="00:00:00:00" outtc="00:00:48:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="56" programno="1628" groupno="1628" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="SPOT" subtitle="EBS Math 홍보&lt;수학은 즐겁고 창의적인 놀?" source="PLUS2_DEC2" mediaid="1B191251" durationtc="00:00:49:00" intc="00:00:00:00" outtc="00:00:48:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="57" programno="1629" groupno="1629" eventmode="1" startmode="0" starttime="20190930 11:19:27:00" input="0" output="3" title="공익광고" subtitle="안전불감증 개선&lt;어느 안전&gt;(30&quot;)" source="PLUS2_DEC1" mediaid="2B190143" durationtc="00:00:30:00" intc="00:00:00:00" outtc="00:00:29:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="58" programno="1629" groupno="1629" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="공익광고" subtitle="안전불감증 개선&lt;어느 안전&gt;(30&quot;)" source="PLUS2_DEC2" mediaid="2B190143" durationtc="00:00:30:00" intc="00:00:00:00" outtc="00:00:29:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="59" programno="1630" groupno="1630" eventmode="1" startmode="0" starttime="20190930 11:19:57:00" input="0" output="3" title="ID" subtitle="EBS PLUS2(2019)" source="PLUS2_DEC1" mediaid="3B190325" durationtc="00:00:20:00" intc="00:00:00:00" outtc="00:00:19:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="60" programno="1630" groupno="1630" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="ID" subtitle="EBS PLUS2(2019)" source="PLUS2_DEC2" mediaid="3B190325" durationtc="00:00:20:00" intc="00:00:00:00" outtc="00:00:19:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="61" programno="1631" groupno="1631" eventmode="1" startmode="0" starttime="20190930 11:20:17:00" input="0" output="3" title="English 서바이벌" subtitle="What? What!" source="PLUS2_DEC1" mediaid="N196B081" durationtc="00:28:05:00" intc="00:00:00:00" outtc="00:28:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="62" programno="1631" groupno="1631" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="English 서바이벌" subtitle="What? What!" source="PLUS2_DEC2" mediaid="N196B081" durationtc="00:28:05:00" intc="00:00:00:00" outtc="00:28:04:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="63" programno="1632" groupno="1632" eventmode="1" startmode="0" starttime="20190930 11:48:22:00" input="0" output="3" title="FILLER" subtitle="익스트림 스포츠 MTB" source="PLUS2_DEC1" mediaid="4B190056" durationtc="00:01:12:00" intc="00:00:00:00" outtc="00:01:11:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="64" programno="1632" groupno="1632" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="FILLER" subtitle="익스트림 스포츠 MTB" source="PLUS2_DEC2" mediaid="4B190056" durationtc="00:01:12:00" intc="00:00:00:00" outtc="00:01:11:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="65" programno="1633" groupno="1633" eventmode="1" startmode="0" starttime="20190930 11:49:34:00" input="0" output="3" title="ID" subtitle="EBS 로고송 MAIN&lt;이진아(2)&gt;(알려줘 Ver.)(" source="PLUS2_DEC1" mediaid="3B190211" durationtc="00:00:27:00" intc="00:00:00:00" outtc="00:00:26:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="66" programno="1633" groupno="1633" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="ID" subtitle="EBS 로고송 MAIN&lt;이진아(2)&gt;(알려줘 Ver.)(" source="PLUS2_DEC2" mediaid="3B190211" durationtc="00:00:27:00" intc="00:00:00:00" outtc="00:00:26:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="67" programno="1634" groupno="1634" eventmode="1" startmode="0" starttime="20190930 11:50:01:00" input="0" output="3" title="보이는 라디오-English Go Go" subtitle="1205회 - 내 영어를 부탁해, 앗뜨거 핫이슈" source="PLUS2_DEC1" mediaid="N199Q005" durationtc="00:39:18:00" intc="00:00:00:00" outtc="00:39:17:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="0" transitiontype="0" transitionrate="1" programtype="0" notes=""/>
    <event serialno="68" programno="1634" groupno="1634" eventmode="2" startmode="4" starttime="20190930 00:00:00:00" input="1" output="3" title="보이는 라디오-English Go Go" subtitle="1205회 - 내 영어를 부탁해, 앗뜨거 핫이슈" source="PLUS2_DEC2" mediaid="N199Q005" durationtc="00:39:18:00" intc="00:00:00:00" outtc="00:39:17:29" videotype="2" audiotype="2" closedcaption="0" voiceadd="1" transitiontype="0" transitionrate="1" programtype="0" notes=""/>